apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-quest.fullname" . }}-config
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"
