{{- if .Values.externalSecrets.enabled }}
# The ClusterSecretStore defines HOW to connect to GCP Secret Manager.
# It leverages the Workload Identity assigned to the ESO controller pods to authenticate.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.projectId | quote }}
      # No credentials/auth block defined, as it inherits GCP Workload Identity implicitly!
---
# The ExternalSecret defines WHAT secret to pull and WHERE to put it.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "code-quest.fullname" . }}-postgres-password
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    # This automatically generates the standard K8s Secret that the App expects (e.g. {{ fullname }}-secret)
    name: {{ include "code-quest.fullname" . }}-secret 
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.gcpSecretName | quote }}
{{- end }}
